all:
	python gen_yahoo.py en_stop_words_887.txt yahoo yahoo-news
	dos2unix yahoo-train yahoo-vocab

clean:
	rm -f *.pyc *-stat *-doc-topic-prob *-topic-word-prob *-topic-count *-word-topic-count *-alpha *-beta
